### ISSUE TITLE
<data> Tag changed to <String>

### ISSUE THREAD

**Issue by kyjdp** [msftrncs/PwshJSONtoPList#5]
<data> Tag changed to <String>

For example:
before:
					<key>Find</key>
					`<data>SEVDSQ==</data>`
					<key>Replace</key>
					`<data>SU1FSQ==</data>`
________________________________________________________________
after:
					<key>Find</key>
					`<string>SEVDSQ==</string>`
					<key>Replace</key>
					`<string>SU1FSQ==</string>`

See Pic:
![pic](https://user-images.githubusercontent.com/6350504/102722823-b6de7e00-433e-11eb-80a7-f7f7b0bb32ff.png)

My programming level, English expression is not very good,

so, I recorded a video demonstration: https://www60.zippyshare.com/v/72znRFfX/file.html

Related documents: https://www60.zippyshare.com/v/JX5BgvUh/file.html

It may be the same as the following question
https://github.com/msftrncs/PwshReadXmlPList/issues/4

**Comment by msftrncs** [comment]
I'm closing this as I think this was fixed with msftrncs/PwshReadXmlPList#4.
